### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 425: ordinal not in range(128)

### ISSUE THREAD

**Issue by jcoetsie** [innogames/igcommit#14]
Hi,

It seems there is a problem with encoding unicode characters, in this case the European Euro Sign €

```
remote: === CheckCommitSummary on 1d03c552 ===
remote: WARNING: commit title not capitalized
remote:
remote:
remote: An error occurred, but the commits are accepted.
remote: Traceback (most recent call last):
remote:   File "/usr/local/lib/python2.7/dist-packages/igcommit/prereceive.py", line 116, in main
remote:     state = Runner().run()
remote:   File "/usr/local/lib/python2.7/dist-packages/igcommit/prereceive.py", line 34, in run
remote:     check.print_problems()
remote:   File "/usr/local/lib/python2.7/dist-packages/igcommit/base_check.py", line 75, in print_problems
remote:     for severity, problem in self.evaluate_problems():
remote:   File "/usr/local/lib/python2.7/dist-packages/igcommit/base_check.py", line 85, in evaluate_problems
remote:     for severity, problem in self.get_problems():
remote:   File "/usr/local/lib/python2.7/dist-packages/igcommit/file_checks.py", line 327, in get_problems
remote:     self.load_func(self.committed_file.get_content().decode('utf-8'))
remote:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
remote:     parser.feed(text)
remote:   File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1651, in feed
remote:     self._parser.Parse(data, 0)
remote: UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 425: ordinal not in range(128)
```

Any idea?

**Comment by jcoetsie** [comment]
Forgot: is on version 2.4

**Comment by hasegeli** [comment]
Do you mean Python 2.4?  It is impossible.  The script requires minimum 2.7.  I recommend using Python 3 for proper Unicode support.

**Comment by jcoetsie** [comment]
No, igcommit 2.4
Python 2.7.12

**Comment by hasegeli** [comment]
I prepared #15.  Do you have possibility to test it?

**Comment by jcoetsie** [comment]
I'll give it a go and let you know

**Comment by jcoetsie** [comment]
Hi,

I just tested it.

With the `master` branch it fails BUT
with the `check_format_unicode` it passes :-)

tx for this quick fix...

Lets release this :-)

**Comment by hasegeli** [comment]
Done.  Thank you for the report.
